apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smc-app
  description: Supplier Management Center
  links:
    - url: https://smc-app-dev-ns.apps.tap.tanzu.projectscions.com/suppliermgmt/entry/ApplicationEntry?SSOID=600104283
      title: Supplier Management Center
      icon: dashboard
  tags:
    - penske-dev-team
    - java
    - spring
    - web
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=smc-app'
spec:
  type: service
  lifecycle: dev-env
  owner: core-smc-team
  system: supplier-management-center

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dev-env
  title: Supplier Management Center
  description: Supplier Management Center
spec:
  owner: core-dev-team
  domain: backend-apps

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john-shiffler
spec:
  profile:
    displayName: John Shiffler
    email: john.shiffler@penske.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [core-dev-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: iswarya-balasubramanian
spec:
  profile:
    displayName: Iswarya Balasubramanian
    email: iswarya.balasubramanian@penske.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [core-dev-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: iswarya-balasubramanian
spec:
  profile:
    displayName: Chandra Thondappa
    email: chandra.thondappa@penske.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [core-dev-team]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: core-dev-team
  description: Core Dev Team
spec:
  type: team
  profile:
    displayName: Core Dev Team
    email: core-dev-team@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff
  parent: core-dev-team
  children: []
